**Numpy tutorial: iterate numpy array using nditer**

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [4]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
np.sum(b,axis=1)

array([1, 5, 9])

***Using normal for loop iteration***

In [6]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


***For loop with flatten***

In [7]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


**nditer**

***C style ordering***

In [8]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


***Fortan style ordering***

In [9]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


***External_loop***

In [10]:
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


**Modify array values while iterating**

In [11]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x

In [12]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

**Iterate two broadcastable arrays concurrently**

In [13]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [14]:
for x, y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [15]:
x = np.arange(27).reshape((3,3,3))
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
x.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [17]:
x.sum(0), x.sum(1), x.sum(2)

(array([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]]),
 array([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]]),
 array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]))